### ISSUE TITLE
Please add a 32x32 display

### ISSUE THREAD

**Issue by GreenBushy** [Krita-Burstflakes/infinite-logics#1]
Please add a 32x32 frame-less display. This will make the resolution of the screens more flexible.

**Comment by Krita-Burstflakes** [comment]
16x16 max display size

**Comment by GreenBushy** [comment]
I see. then will you add a display the size of 1 block or not?

**Comment by Krita-Burstflakes** [comment]
зачем?

**Comment by GreenBushy** [comment]
В первом сообщении написано.
Да я реально хочу такие дисплеи.

**Comment by Krita-Burstflakes** [comment]
мне их легко сделать, но смысл если это сделает сложнее вывод изображения?

**Comment by GreenBushy** [comment]
Нет не сделает. Так как есть другие дисплеи. Смысл состоит в том что с помощью этого можно сделать много чтук. На пример что-то в роде кастомных кнопок, создание экрана с разрешением сходным с разрешением ретро консоли, создание иллюзии блока с абсолютно любой логикой без модов (почти), с любой текстурой с помощью мировых процессоров. Могу ещё накинуть.

**Comment by Krita-Burstflakes** [comment]
![image](https://github.com/Krita-Burstflakes/infinite-logics/assets/130148398/84dca6d7-80ef-415f-b9b2-a2a8f7a33559)

**Comment by GreenBushy** [comment]
Предположительно тот что с лева дисплей из-за сглаживания. Спасибо за реализацию идеи, буду ждать обновления. (юнит выглядит необычно).

**Comment by Krita-Burstflakes** [comment]
обновлено
